In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/codeforcauseorg/ML-Bootcamp-July/master/datasets/mushrooms.csv")

In [3]:
data


type cap_shape cap_surface  ... spore_print_color population habitat
0       p         x           s  ...                 k          s       u
1       e         x           s  ...                 n          n       g
2       e         b           s  ...                 n          n       m
3       p         x           y  ...                 k          s       u
4       e         x           s  ...                 n          a       g
...   ...       ...         ...  ...               ...        ...     ...
8119    e         k           s  ...                 b          c       l
8120    e         x           s  ...                 b          v       l
8121    e         f           s  ...                 b          c       l
8122    p         k           y  ...                 w          v       l
8123    e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

In [4]:
#convert to numeric data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [5]:
le = LabelEncoder()

In [6]:
ds = data.apply(func = le.fit_transform) #apply label encoder function to each and every column

In [7]:
ds.head()

type  cap_shape  cap_surface  ...  spore_print_color  population  habitat
0     1          5            2  ...                  2           3        5
1     0          5            2  ...                  3           2        1
2     0          0            2  ...                  3           2        3
3     1          5            3  ...                  2           3        5
4     0          5            2  ...                  3           0        1

[5 rows x 23 columns]

In [8]:
d = ds.values
d

array([[1, 5, 2, ..., 2, 3, 5],
       [0, 5, 2, ..., 3, 2, 1],
       [0, 0, 2, ..., 3, 2, 3],
       ...,
       [0, 2, 2, ..., 0, 1, 2],
       [1, 3, 3, ..., 7, 4, 2],
       [0, 5, 2, ..., 4, 1, 2]])

In [9]:
x = d[:,1:]
y = d[:,0]

In [10]:
x.shape, y.shape

((8124, 22), (8124,))

8124

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.33 , random_state = 42)

In [12]:
np.sum(y_train==0)

2830

In [16]:
#Custom Implementation of Naive Bayes

class CustomNaiveBayes:

  def fit(self, x,y):
    self.x_train = x
    self.y_train = y

  def prior_prob(self, label): #label = which class the property is being calculated
    total = self.y_train.shape[0]
    class_examples = np.sum(self.y_train == label)
    return class_examples/ total

  #P(Xi|label) = for feature in ith column for a single example
  def condtitional_prob(self, feature_col, feature_val, label):
    #out of all the values which feature has this particular feature val in the feature col 
    x_filtered = self.x_train[self.y_train == label] #all the examples in class label 
    numerator = np.sum(x_filtered[:,feature_col] == feature_val)
    denominator = len(x_filtered)
    return numerator/denominator

  #repeat this for all the features that we have
  def predict_point(self, x_test):
    #single example with n features
    classes = np.unique(self.y_train)
    n_features = self.x_train.shape[1]
    post = [] #posterior probability
    #post prob for each class and then calculate max out of them
    for label in classes:
      #post_prob = prioir*likelihood
      likehood = 1.0
      for feature in range(n_features):
        cond = self.condtitional_prob(feature, x_test[feature], label)
        likehood *= cond
      prior = self.prior_prob(label)
      p = prior*likehood
      post.append(p)
    return np.argmax(post)

  def predict(self, x_test):
    res = []
    for point in x_test:
      res.append(self.predict_point(point))
    return np.array(res)

  def score(self, x_test, y_test):
    return (self.predict(x_test) == y_test).mean()


In [18]:
model = CustomNaiveBayes()
model.fit(x_train, y_train)
model.predict(x_test[:10])

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [19]:
y_test[:10]

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [20]:
model.score(x_test,y_test)*100

99.73890339425587